swagger: '2.0'
info:
  description: ''
  title: sample
paths:
  '/rooms/{room-id}':
    get:
      deprecated: true
      description: ''
      parameters:
        - name: room-id
          in: path
          type: integer
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 404
              comment:
                type: string
                example: 404
      security:
        - api_key: []
  '/rooms/{room-id}/doors':
    get:
      deprecated: true
      responses:
        '200':
          schema:
            type: array
      security:
        - api_key: []
    post:
      responses:
        '200':
          schema:
            type: object
      security:
        - api_key: []
