swagger: '2.0'
info:
  description: sample
  title: sample
paths:
  '/rooms/{room-id}': {}
  '/rooms/{room-id}/doors':
    post:
      responses:
        '200':
          schema:
            type: object
      security:
        - api_key: []
